#pragma once

namespace rfapp {

enum class CategoryType : int
{
    TOP_LEVEL_DATA_SETS,
    TOP_LEVEL_ANALYSIS,
    TOP_LEVEL_REPLAY_GROUPS,
    TOP_LEVEL_REPLAY_SOURCES,
    TOP_LEVEL_VIDEO_SOURCES,
    TOP_LEVEL_SESSION,

    ITEM_DATA_SET,
    ITEM_ANALYSIS,
    ITEM_REPLAY_GROUP,
    ITEM_REPLAY_SOURCE,
    ITEM_VIDEO_SOURCE,
};

}
