#pragma once

namespace uh {

enum class CategoryType : int
{
    TOP_LEVEL_ANALYSIS,
    TOP_LEVEL_RECORDING_GROUPS,
    TOP_LEVEL_RECORDING_SOURCES,
    TOP_LEVEL_VIDEO_SOURCES,
    TOP_LEVEL_ACTIVE_RECORDING,
    RECORDING_GROUP_ITEM,
    RECORDING_SOURCE_ITEM,
    VIDEO_SOURCE_ITEM,
};

}

